# Unit 4. 출력층 설계와 신경망 평가

In [1]:
import numpy as np
import seaborn as sns

In [2]:
iris = sns.load_dataset('iris')
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

- Label Encoding

In [3]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(iris.species)
target = le.transform(iris.species)
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [4]:
iris['target'] = le.fit_transform(iris.species)
iris.head()

sepal_length  sepal_width  petal_length  petal_width species  target
0           5.1          3.5           1.4          0.2  setosa       0
1           4.9          3.0           1.4          0.2  setosa       0
2           4.7          3.2           1.3          0.2  setosa       0
3           4.6          3.1           1.5          0.2  setosa       0
4           5.0          3.6           1.4          0.2  setosa       0

In [5]:
np.unique(iris.target, return_counts=True)

(array([0, 1, 2]), array([50, 50, 50]))

- One-hot encoding

In [6]:
from tensorflow.keras.utils import to_categorical

Y_encoded = to_categorical(iris.target)
Y_encoded[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [7]:
Y_encoded[-5:]

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]], dtype=float32)

- 신경망 평가

In [8]:
from sklearn.datasets import load_digits

mnist = load_digits()

In [9]:
mnist.target[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# Is it seven?
target = np.array(mnist.target == 7, dtype=np.int32)
target[:10]

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int32)

In [11]:
prediction = np.zeros_like(target)
prediction[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [12]:
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    mnist.data, target, stratify=target, random_state=2022
)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1347, 64), (450, 64), (1347,), (450,))

In [14]:
pred = np.zeros_like(y_test)
confusion_matrix(y_test, pred)

array([[405,   0],
       [ 45,   0]])

In [15]:
accuracy_score(y_test, pred)

0.9